local_backend: true

backend:
  name: git-gateway

site_url: https://epiclandscapedesigns.netlify.app

publish_mode: editorial_workflow
media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'hero'
    label: 'Hero Section'
    label_singular: 'Hero'
    description: 'Manage the hero section content'
    files:
      - file: '_data/hero.yml'
        label: 'Hero Content'
        name: 'hero'
        fields:
          - { label: 'Subtitle', name: 'subtitle', widget: 'string', default: 'One Epic Landscape at a Time' }
          - { label: 'Button Text', name: 'button_text', widget: 'string', default: 'Get Free Consultation' }
          - { label: 'Button Link', name: 'button_link', widget: 'string', default: '/contact' }
          - { label: 'Video Link', name: 'video_link', widget: 'string', default: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' }
          - { label: 'Background Image', name: 'background_image', widget: 'image', default: 'assets/images/hero-bg.jpg' }
          - { label: 'Thumbnail Image', name: 'thumbnail_image', widget: 'image', default: 'assets/images/hero-bg.jpg' }

  - name: 'Company'
    label: 'Company Information'
    label_singular: 'Contact'
    description: 'Manage contact information and settings'
    files:
      - file: '_data/company.yml'
        label: 'Company Details'
        name: 'Company'
        fields:
          - { label: 'Name', name: 'name', widget: 'string', default: 'Epic Landscape Designs' }
          - { label: 'Email', name: 'email', widget: 'string', default: 'info@epiclandscapedesigns.com.au' }

  - name: 'about'
    label: 'About Section'
    label_singular: 'About'
    description: 'Manage the about section content'
    files:
      - file: '_data/about.yml'
        label: 'About Content'
        name: 'about'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text'  }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Image Alt', name: 'image_alt', widget: 'string' }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    description: 'Manage the projects section content'
    files:
      - file: '_data/projects.yml'
        label: 'Projects'
        name: 'projects'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'string' }
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            summary: '{{fields.project_name}}'
            fields:
              - { label: 'Project Name', name: 'project_name', widget: 'string' }
              - { label: 'Project Summary', name: 'project_summary', widget: 'text' }
              - { label: 'Project Image', name: 'project_image', widget: 'image' }
              - { label: 'Project Image Alt Text', name: 'project_image_alt', widget: 'string' }
          